services:
  net:
    image: alpine:latest
    command: /bin/sh -c "tail -f /dev/null"
  postgres:
    restart: always
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_DB: cmp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "tail -f /dev/null"
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh:/home/user/.ssh
      - /var/run/docker.sock:/var/run/docker.sock:rw
    network_mode: service:net
